[workspace]
members = [
    "mining-app",
    "operator_runtime",
    "operator/datasource_operator",
    "operator/indicator_operator",
    "operator/expression_operator",
    "operator/kline_visualization_operator",
    "operator/line_chart_operator",
    "operator/ollama_operator",
    "operator/cumsum_operator",
    "operator/shift_add_operator",
    "operator_executor_client",
    "operator_sdk",
    "operator_runtime_server",
]

resolver = "2"

[profile.release]
strip = "symbols"
opt-level = 3
codegen-units = 1

[profile.dev]
strip = false
opt-level = 0
codegen-units = 1